# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  ◈ HYPRLAND CONFIGURATION
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# Sourcing modularized configs
source = /home/_null/.config/hypr/modules/monitors.conf
source = /home/_null/.config/hypr/modules/colors.conf
source = /home/_null/.config/hypr/modules/env.conf
source = /home/_null/.config/hypr/modules/autostart.conf
source = /home/_null/.config/hypr/modules/settings.conf
source = /home/_null/.config/hypr/modules/animations.conf
source = /home/_null/.config/hypr/modules/rules.conf
source = /home/_null/.config/hypr/modules/keybinds.conf

# Custom user preferences
source = /home/_null/.config/hypr/user_prefs.conf
